server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com/
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
          - Path=/user/{username}
          - Method=GET
          filters:
          - SetPath=/user/username/{username}
        - id: user-service-create
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user
            - Method=POST
          filters:
            - SetPath=/user
        - id: user-service-update
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user/edit/{username}
            - Method=PUT
          filters:
            - SetPath=/user/username/{username}
        - id: user-service-delete
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user/delete/{username}
            - Method=DELETE
          filters:
            - SetPath=/user/username/{username}



        - id: playlist-service
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8083}
          predicates:
          - Path=/playlist/{id}
          - Method=GET
          filters:
          - SetPath=/playlist/id/{id}
        - id: playlist-service-all
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/playlist/all
            - Method=GET
          filters:
            - SetPath=/playlist/all
        - id: playlist-service-create
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/playlist
            - Method=POST
          filters:
            - SetPath=/playlist
        - id: playlist-service-update
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/playlist/edit/{id}
            - Method=PUT
          filters:
            - SetPath=/playlist/id/{id}
        - id: playlist-service-delete
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/playlist/delete/{id}
            - Method=DELETE
          filters:
            - SetPath=/playlist/id/{id}



        - id: rating-service-create
          uri: http://${RATING_SERVICE_BASEURL:localhost:8082}
          predicates:
          - Path=/rating
          - Method=POST
          filters:
          - SetPath=/rating
        - id: rating-service-delete
          uri: http://${RATING_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rating/delete/{id}
            - Method=DELETE
          filters:
            - SetPath=/rating/id/{id}
        - id: rating-service-update
          uri: http://${RATING_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rating/edit/{id}
            - Method=PUT
          filters:
            - SetPath=/rating/id/{id}



        - id: music-podcast-service-all
          uri: http://${MUSICPODCAST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/musicpodcast/all
            - Method=GET
          filters:
            - SetPath=/musicpodcast/all
        - id: music-podcast-service-songs
          uri: http://${MUSICPODCAST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/musicpodcast/allsongs
            - Method=GET
          filters:
            - SetPath=/musicpodcast/songs
        - id: music-podcast-service-podcasts
          uri: http://${MUSICPODCAST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/musicpodcast/allpodcasts
            - Method=GET
          filters:
            - SetPath=/musicpodcast/podcasts
        - id: music-podcast-service-song
          uri: http://${MUSICPODCAST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/musicpodcast/{uniqueIdentifier}
            - Method=GET
          filters:
            - SetPath=/musicpodcast/id/{uniqueIdentifier}
        - id: music-podcast-service-ratings-username
          uri: http://${MUSICPODCAST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/musicpodcast/ratings/{username}
            - Method=GET
          filters:
            - SetPath=/musicpodcast/ratings/{username}
        - id: music-podcast-service-ratings-username-uniqueidentifier
          uri: http://${MUSICPODCAST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/musicpodcast/rating/{username}/{uniqueIdentifier}
            - Method=GET
          filters:
            - SetPath=/musicpodcast/rating/{username}/{uniqueIdentifier}
